[train] Refactor `AcceleratorSetupCallback` to use `before_init_train_context` (#56509)
This fixes an issue in which the CUDA context is not properly configured
during import deserialization.

```
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":49, please report a bug to PyTorch. device=1, num_gpus=
```

The fix is to update the CUDA_VISIBLE_DEVICE sharing logic to be implemented in before_init_train_context instead of after_worker_group_start, so that torch.cuda initialization happens after the environment variable is set up properly.

---------

Signed-off-by: Matthew Deng <matthew.j.deng@gmail.com>
Signed-off-by: Justin Yu <justinvyu@anyscale.com>
Co-authored-by: Justin Yu <justinvyu@anyscale.com>
Signed-off-by: elliot-barn <elliot.barnwell@anyscale.com>