[Core] Avoid shadowing member var in ProbeState (#63892)
## Description
The ubsan tests were failing in release at compile time due to throwing
error on warning of shadowed variable:
```
[2026-06-04T19:43:48Z] In file included from src/ray/asio/io_context_monitor.cc:15:
--
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h: In constructor 'ray::IOContextMonitor::ProbeState::ProbeState(std::string, instrumented_io_context&, std::shared_ptr<ray::ClockInterface>)':
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:64:48: error: declaration of 'clock' shadows a member of 'ray::IOContextMonitor::ProbeState' [-Werror=shadow]
  | [2026-06-04T19:43:48Z]    64 \|                std::shared_ptr<ClockInterface> clock)
  | [2026-06-04T19:43:48Z]       \|                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:69:43: note: shadowed declaration is here
  | [2026-06-04T19:43:48Z]    69 \|     const std::shared_ptr<ClockInterface> clock;
  | [2026-06-04T19:43:48Z]       \|                                           ^~~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:63:41: error: declaration of 'io_context' shadows a member of 'ray::IOContextMonitor::ProbeState' [-Werror=shadow]
  | [2026-06-04T19:43:48Z]    63 \|                instrumented_io_context &io_context,
  | [2026-06-04T19:43:48Z]       \|                ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:68:30: note: shadowed declaration is here
  | [2026-06-04T19:43:48Z]    68 \|     instrumented_io_context &io_context;
  | [2026-06-04T19:43:48Z]       \|                              ^~~~~~~~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:62:28: error: declaration of 'name' shadows a member of 'ray::IOContextMonitor::ProbeState' [-Werror=shadow]
  | [2026-06-04T19:43:48Z]    62 \|     ProbeState(std::string name,
  | [2026-06-04T19:43:48Z]       \|                ~~~~~~~~~~~~^~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:67:23: note: shadowed declaration is here
  | [2026-06-04T19:43:48Z]    67 \|     const std::string name;
  | [2026-06-04T19:43:48Z]       \|                       ^~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h: In constructor 'ray::IOContextMonitor::ProbeState::ProbeState(std::string, instrumented_io_context&, std::shared_ptr<ray::ClockInterface>)':
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:64:48: error: declaration of 'clock' shadows a member of 'ray::IOContextMonitor::ProbeState' [-Werror=shadow]
  | [2026-06-04T19:43:48Z]    64 \|                std::shared_ptr<ClockInterface> clock)
  | [2026-06-04T19:43:48Z]       \|                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:69:43: note: shadowed declaration is here
  | [2026-06-04T19:43:48Z]    69 \|     const std::shared_ptr<ClockInterface> clock;
  | [2026-06-04T19:43:48Z]       \|                                           ^~~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:63:41: error: declaration of 'io_context' shadows a member of 'ray::IOContextMonitor::ProbeState' [-Werror=shadow]
  | [2026-06-04T19:43:48Z]    63 \|                instrumented_io_context &io_context,
  | [2026-06-04T19:43:48Z]       \|                ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:68:30: note: shadowed declaration is here
  | [2026-06-04T19:43:48Z]    68 \|     instrumented_io_context &io_context;
  | [2026-06-04T19:43:48Z]       \|                              ^~~~~~~~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:62:28: error: declaration of 'name' shadows a member of 'ray::IOContextMonitor::ProbeState' [-Werror=shadow]
  | [2026-06-04T19:43:48Z]    62 \|     ProbeState(std::string name,
  | [2026-06-04T19:43:48Z]       \|                ~~~~~~~~~~~~^~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:67:23: note: shadowed declaration is here
  | [2026-06-04T19:43:48Z]    67 \|     const std::string name;
  | [2026-06-04T19:43:48Z]       \|                       ^~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h: In constructor 'ray::IOContextMonitor::ProbeState::ProbeState(std::string, instrumented_io_context&, std::shared_ptr<ray::ClockInterface>)':
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:64:48: error: declaration of 'clock' shadows a member of 'ray::IOContextMonitor::ProbeState' [-Werror=shadow]
  | [2026-06-04T19:43:48Z]    64 \|                std::shared_ptr<ClockInterface> clock)
  | [2026-06-04T19:43:48Z]       \|                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:69:43: note: shadowed declaration is here
  | [2026-06-04T19:43:48Z]    69 \|     const std::shared_ptr<ClockInterface> clock;
  | [2026-06-04T19:43:48Z]       \|                                           ^~~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:63:41: error: declaration of 'io_context' shadows a member of 'ray::IOContextMonitor::ProbeState' [-Werror=shadow]
  | [2026-06-04T19:43:48Z]    63 \|                instrumented_io_context &io_context,
  | [2026-06-04T19:43:48Z]       \|                ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:68:30: note: shadowed declaration is here
  | [2026-06-04T19:43:48Z]    68 \|     instrumented_io_context &io_context;
  | [2026-06-04T19:43:48Z]       \|                              ^~~~~~~~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:62:28: error: declaration of 'name' shadows a member of 'ray::IOContextMonitor::ProbeState' [-Werror=shadow]
  | [2026-06-04T19:43:48Z]    62 \|     ProbeState(std::string name,
  | [2026-06-04T19:43:48Z]       \|                ~~~~~~~~~~~~^~~~
  | [2026-06-04T19:43:48Z] bazel-out/k8-opt/bin/src/ray/asio/_virtual_includes/io_context_monitor/ray/asio/io_context_monitor.h:67:23: note: shadowed declaration is here
  | [2026-06-04T19:43:48Z]    67 \|     const std::string name;
  | [2026-06-04T19:43:48Z]       \|                       ^~~~
  | [2026-06-04T19:43:48Z] cc1plus: all warnings being treated as errors
```

This PR addresses this issue by renaming the constructor arguments and
adds a missing dependency for an include in
`memory_monitor_test_fixture`.


## Related issues

## Additional information

Signed-off-by: davik <davik@anyscale.com>
Co-authored-by: davik <davik@anyscale.com>