[core] Output the error log on the driver side if the failed task will still retry (#56472)
If the failed task will still retry, we should print the error log on
the driver side; otherwise, it’s not necessary, since ray.get can
retrieve it. This is for better observability.

Note that this feature can be disabled by `export
RAY_enable_output_error_log_if_still_retry=0`.

Tried the example in the issue
Before this PR:
```
2025-09-11 22:45:16,569  INFO logging.py:295 -- Registered dataset logger for dataset dataset_2_0
2025-09-11 22:45:16,590  INFO streaming_executor.py:159 -- Starting execution of Dataset dataset_2_0. Full logs are in /tmp/ray/session_2025-09-11_22-44-45_753182_597098/logs/ray-data
2025-09-11 22:45:16,590  INFO streaming_executor.py:160 -- Execution plan of Dataset dataset_2_0: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange] -> ActorPoolMapOperator[MapBatches(Embed)]
Running 0: 0.00 row [00:00, ? row/s][2025-09-11 22:45:16,626 E 597098 597098] core_worker.cc:2151: Actor with class name: 'MapWorker(MapBatches(Embed))' and ID: '80871f7866b6f8a9cd68308801000000' has constructor arguments in the object store and max_restarts > 0. If the arguments in the object store go out of scope or are lost, the actor restart will fail. See https://github.com/ray-project/ray/issues/53727 for more details.

- ReadRange->SplitBlocks(256) 1: 0.00 row [00:00, ?
 row/s]
- MapBatches(E2025-09-11 22:45:16,6280, ? WARNING resource_manager.py:134 -- ⚠️  Ray's object store is configured to use only 10.2% of available memory (186.3GiB out of 1823.1GiB total). For optimal Ray Data performance, we recommend setting the object store to at least 50% of available memory. You can do this by setting the 'object_store_memory' parameter when calling ray.init() or by setting the RAY_DEFAULT_OBJECT_STORE_MEMORY_PROPORTION environment variable.
Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 10.0B/93.1GB object store: : 0.00 row [00:01, ? Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 10.0B/93.1GB object store: : 0.00 row [00:01, ? Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 10.0B/93.1GB object store: : 0.00 row [00:01, ? row/s]
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 10.0B object store: : 0.00 row [00:01, ? row/s
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 10.0B object store: : 1.00 row [00:01, 1.03s/
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 10.0B object store: : 1.00 row [00:01, 1.03s/
row]
- MapBatches(Embed): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/7 objects local]:
 : 0.00 row [00:0
- MapBatches(Embed): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/7 objects local]:
 : 0.00 row [00:0
- MapBatches(Embed): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/7 objects local]:
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 9.0B object store: : 1.00 row [00:02, 1.03s/ r
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 9.0B object store: : 1.00 row [00:02, 1.03s/ r
ow]
- MapBatches(Embed): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/27 objects local]
: : 0.00 row [00:
- MapBatches(Embed): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 9.0B/93.1GB object store: : 0.00 row [00:02, ? rRunning Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 9.0B/93.1GB object store: : 0.00 row [00:02, ? row/s]

- MapBatches(Embed): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/49 objects local]
: : 0.00 row [00:
- MapBatches(Embe                                                                                     Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 0.0B/93.1GB object store: : 0.00 row [00:03, ? rRunning Dataset:                                                                                                       Running Dataset:
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store: : 1.00 row [00:03, 1.03s/ r
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store: : 1.00 row [02025-09-11 22:45:20,489       INFO streaming_executor.py:279 -- ✔️  Dataset dataset_2_0 execution finished in 3.90 seconds

                                                                                                                       ✔️  Dataset datas

- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store: : 1.00 row [00:03, 1.03s/ r
- ReadRange->SplitBlocks(256): Tasks: 0; Actors: 0; Queued blocks: 0; Resources: 0.0 CPU, 0.0B object store: : 1.00 row [00:03, 1.03s/ r
- ReadRange->Spli                                                                                                      - ReadRange->Spli
- MapBatches(Embe
```

After this pr:
```
/workspace/ray/python/ray/_private/worker.py:1987: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
2025-09-19 21:18:58,059 INFO logging.py:295 -- Registered dataset logger for dataset dataset_2_0
2025-09-19 21:18:58,101 INFO streaming_executor.py:159 -- Starting execution of Dataset dataset_2_0. Full logs are in /tmp/ray/session_2025-09-19_21-18-47_658581_2956326/logs/ray-data
2025-09-19 21:18:58,101 INFO streaming_executor.py:160 -- Execution plan of Dataset dataset_2_0: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange] -> ActorPoolMapOperator[MapBatches(Embed)]
Running 0: 0.00 row [00:00, ? row/s][2025-09-19 21:18:58,205 E 2956326 2956326] core_worker.cc:2151: Actor with class name: 'MapWorker(MapBatches(Embed))' and ID: 'f1a874d3f4dd2fd81467ccf101000000' has constructor arguments in the object store and max_restarts > 0. If the arguments in the object store go out of scope or are lost, the actor restart will fail. See https://github.com/ray-project/ray/issues/53727 for more details.
                                                2025-09-19 21:18:58,211 WARNING resource_manager.py:134 -- ⚠️  Ray's object store is configured to use only 10.2% of available memory (186.3GiB out of 1824.3GiB total). For optimal Ray Data performance, we recommend setting the object store to at least 50% of available memory. You can do this by setting the 'object_store_memory' parameter when calling ray.init() or by setting the RAY_DEFAULT_OBJECT_STORE_MEMORY_PROPORTION environment variable.
Running Dataset: dataset_2_0. Active & requested resources: 1/128 CPU, 256.0MB/93.1GB object store (pendingRunning Dataset: dataset_2_0. Active & requested resources: 1/128 CPU, 256.0MB/93.1GB object store (pending: 1 CPU): : 0.00 row [00:01, ? row/s]
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 256.0MB object st
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 256.0MB object st
ore: : 0.00 row [00:01, ? row/s]
                                                                                                                                                : 1 (running=0, restarting=0, pending=1); Queued blocks: 0; Resources:

(raylet) Task MapWorker(MapBatches(Embed)).submit failed. There are infinite retries remaining, so the task will be retried. Error: User exception:
nner/plan_udf_map_op.py", line 486, in transform_fn
    res = fn(batch)
          ^^^^^^^^^
  File "/workspace/ray/python/ray/data/_internal/planner/plan_udf_map_op.py", line 386, in _wrapped_udf_map_fn
    _try_wrap_udf_exception(e)
  File "/workspace/ray/python/ray/data/_internal/planner/plan_udf_map_op.py", line 410, in _try_wrap_udf_exception
    raise UserCodeException("UDF failed to process a data block.") from e
ray.exceptions.UserCodeException: UDF failed to process a data block.
Running Dataset: dataset_2_0. Active & requested resources: 1/128 CPU, 256.0MB/93.1GB object store (pending: 1 CPU): : 0.00 row [00:01, ? row/s]
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 256.0MB object st
Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 9.0B/93.1GB object store: : 0.00 rowRunning Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 9.0B/93.1GB object store: : 0.00 rowRunning Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 9.0B/93.1GB object store: : 0.00 row [00:02, ? row/s]
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 9.0B object store
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 9.0B object store
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 9.0B object store
: : 1.00 row [00:02, 2.10s/ row]
- MapBatches(Embed): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/13 ob
Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 9.0B/93.1GB object store: : 0.00 row [00:03, ? row/s]d): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/13 ob
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 8.0B object store
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 8.0B object store
: : 1.00 row [00:03, 2.10s/ row]
Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 0.0B/93.1GB object store: : 0.00 rowRunning Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 0.0B/93.1GB object store:   0%| | 0.Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 0.0B/93.1GB object store: 100%|█| 1.

- MapBatches(Embed): Tasks: 2; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/65 ob
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store
Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 0.0B/93.1GB object store: 100%|█| 1.
Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 0.0B/93.1GB object store: 100%|█| 1.
- ReadRange->SplitBlocks(256): T2025-09-19 21:19:05,248uINFO streaming_executor.py:279 -- ✔️  Dataset dataset_2_0 execution finished in 7.14 seconds; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/201 o

✔️  Dataset dataset_2_0 execution finished in 7.14 seconds: 100%|█████| 1.00/1.00 [00:07<00:00, 7.14s/ row]

- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store
- ReadRange->SplitBlocks(256): Tasks: 0; Actors: 0; Queued blocks: 0; Resources: 0.0 CPU, 0.0B object store
- ReadRange->SplitBlocks(256): Tasks: 0; Actors: 0; Queued blocks: 0; Resources: 0.0 CPU, 0.0B object store
- MapBatches(Embed): Tasks: 0; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/256 o
(raylet) Task MapWorker(MapBatches(Embed)).submit failed. There are infinite retries remaining, so the task will be retried. Error: User exception:
nner/plan_udf_map_op.py", line 486, in transform_fn
    res = fn(batch)
          ^^^^^^^^^
  File "/workspace/ray/python/ray/data/_internal/planner/plan_udf_map_op.py", line 386, in _wrapped_udf_map_fn
    _try_wrap_udf_exception(e)
  File "/workspace/ray/python/ray/data/_internal/planner/plan_udf_map_op.py", line 410, in _try_wrap_udf_exception
    raise UserCodeException("UDF failed to process a data block.") from e
ray.exceptions.UserCodeException: UDF failed to process a data block.
```

Signed-off-by: Marco Stephan <marco@magic.dev>