[ci] Upgrade numba, remove windows-specific constraint (#31394)
The latest release of numpy is incompatible with the currently pinned version of numba for windows. E.g. the `np.long` alias has been removed, leading to `AttributeError: module 'numpy' has no attribute 'long'`.

It's not clear if this separate numba pin is still needed, so this PR removes the OS-specific pin and upgrades numba to the latest patch release. If this fails, we can pin numpy for windows tests instead until we found a resolution.

Signed-off-by: Kai Fricke <kai@anyscale.com>
Signed-off-by: Shomil Jain <shomil@anyscale.com>