[Data] Always print traceback for internal exceptions (#46647)
If Ray Data raises an internal error (not from the user-provided UDF),
then the traceback is mostly hidden.
```
2024-07-15 20:45:45,956 ERROR exceptions.py:73 -- Exception occurred in Ray Data or Ray Core internal code. If you continue to see this error, please open an issue on the Ray project GitHub page with the full stack trace below: https://github.com/ray-project/ray/issues/new/choose
ray.data.exceptions.SystemException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/tests/1.py", line 3, in <module>
    ray.data.range(1).materialize()
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/dataset.py", line 4599, in materialize
    copy._plan.execute()
  File "/Users/balaji/Documents/GitHub/ray/python/ray/data/exceptions.py", line 90, in handle_trace
    raise e.with_traceback(None) from SystemException()
RuntimeError: Mock internal error
```

This output isn't helpful for debugging, so this PR changes the behavior
so that the full traceback is printed for all internal errors.

Signed-off-by: Balaji Veeramani <balaji@anyscale.com>