[serve] Move utility functions from constants to constants_utils + increase readability of constants (#54944)
- Move utility functions from `constants.py` to separate utility file
`constants_utils.py`.
- Increase readability of `constants.py` by introduction utility
functions for processing environment variables.
- The behavior of the constants remains unchanged (only error messages
are different), e.g

before: 
```
ValueError: invalid literal for int() with base 10: '0.1'
```
after: 
```
ValueError: Environment variable `RAY_SERVE_DEFAULT_HTTP_PORT` value `0.1` cannot be converted to `int`!
```
before: 
```
AssertionError: Got unexpected value 0 for MAX_CACHED_HANDLES environment variable. MAX_CACHED_HANDLES must be positive.
```
after:
```
ValueError: Got unexpected value `0` for `MAX_CACHED_HANDLES` environment variable! Expected positive `int`.
```

---
Overall, I tried not to change the existing behavior. However, there are
some suggestions for further improvements of the serve constants:
1. Use `RAY_SERVE_` prefix for all env variables. Now, some of them have
it, some - haven't (e.g. `RAY_SERVE_HTTP_PROXY_CALLBACK_IMPORT_PATH` vs
`CONTROLLER_MAX_CONCURRENCY`). It can be confusing. With persistent
naming, readability of constants can be improved and variables will have
consistent naming.
2. Variables which use `or value` silently replaces wrong value for some
variables, e.g.
`float(os.getenv("RAY_SERVE_PROXY_HEALTH_CHECK_TIMEOUT_S", 10)) or 10`
will replace set `0` to `10` without any warning. Would it be better to
just require positive value instead?
3. In the following example 2 env variables are used to fill
`RAY_SERVE_REQUEST_PROCESSING_TIMEOUT_S`. Would one variable be better?
```
RAY_SERVE_REQUEST_PROCESSING_TIMEOUT_S = (
    get_env_float("RAY_SERVE_REQUEST_PROCESSING_TIMEOUT_S", 0)
    or get_env_float("SERVE_REQUEST_PROCESSING_TIMEOUT_S", 0)
    or None
)
```
---------

Signed-off-by: axreldable <aleksei.starikov.ax@gmail.com>