[data] Skip test_daft for pyarrow version >= 14 (#53210)
<!-- Thank you for your contribution! Please review
https://github.com/ray-project/ray/blob/master/CONTRIBUTING.rst before
opening a pull request. -->

<!-- Please add a reviewer to the assignee section when you create a PR.
If you don't have the access to it, we will shortly find a reviewer and
assign them to your PR. -->

## Why are these changes needed?

<!-- Please give a short summary of the change and the problem this
solves. -->

Skip test_daft for pyarrow version >= 14

```
[2025-05-21T17:20:28Z] python/ray/data/tests/test_daft.py::test_daft_round_trip FAILED          [100%]
  | [2025-05-21T17:20:28Z]
  | [2025-05-21T17:20:28Z] =================================== FAILURES ===================================
  | [2025-05-21T17:20:28Z] _____________________________ test_daft_round_trip _____________________________
  | [2025-05-21T17:20:28Z]
  | [2025-05-21T17:20:28Z] ray_start = RayContext(dashboard_url='127.0.0.1:8265', python_version='3.9.21', ray_version='3.0.0.dev0', ray_commit='{{RAY_COMMIT_SHA}}')
  | [2025-05-21T17:20:28Z]
  | [2025-05-21T17:20:28Z]     def test_daft_round_trip(ray_start):
  | [2025-05-21T17:20:28Z]         import daft
  | [2025-05-21T17:20:28Z]         import numpy as np
  | [2025-05-21T17:20:28Z]         import pandas as pd
  | [2025-05-21T17:20:28Z]
  | [2025-05-21T17:20:28Z]         data = {
  | [2025-05-21T17:20:28Z]             "int_col": list(range(128)),
  | [2025-05-21T17:20:28Z]             "str_col": [str(i) for i in range(128)],
  | [2025-05-21T17:20:28Z]             "nested_list_col": [[i] * 3 for i in range(128)],
  | [2025-05-21T17:20:28Z]             "tensor_col": [np.array([[i] * 3] * 3) for i in range(128)],
  | [2025-05-21T17:20:28Z]         }
  | [2025-05-21T17:20:28Z] >       df = daft.from_pydict(data)
  | [2025-05-21T17:20:28Z]
  | [2025-05-21T17:20:28Z] python/ray/data/tests/test_daft.py:27:
  | [2025-05-21T17:20:28Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  | [2025-05-21T17:20:28Z] /opt/miniconda/lib/python3.9/site-packages/daft/convert.py:80: in from_pydict
  | [2025-05-21T17:20:28Z]     return DataFrame._from_pydict(data)
  | [2025-05-21T17:20:28Z] /opt/miniconda/lib/python3.9/site-packages/daft/dataframe/dataframe.py:520: in _from_pydict
  | [2025-05-21T17:20:28Z]     return cls._from_tables(data_micropartition)
  | [2025-05-21T17:20:28Z] /opt/miniconda/lib/python3.9/site-packages/daft/dataframe/dataframe.py:572: in _from_tables
  | [2025-05-21T17:20:28Z]     df._populate_preview()
  | [2025-05-21T17:20:28Z] /opt/miniconda/lib/python3.9/site-packages/daft/dataframe/dataframe.py:473: in _populate_preview
  | [2025-05-21T17:20:28Z]     preview_parts = self._result._get_preview_micropartitions(self._num_preview_rows)
  | [2025-05-21T17:20:28Z] /opt/miniconda/lib/python3.9/site-packages/daft/runners/ray_runner.py:272: in _get_preview_micropartitions
  | [2025-05-21T17:20:28Z]     part: MicroPartition = ray.get(ref)
  | [2025-05-21T17:20:28Z] /rayci/python/ray/_private/auto_init_hook.py:21: in auto_init_wrapper
  | [2025-05-21T17:20:28Z]     return fn(*args, **kwargs)
  | [2025-05-21T17:20:28Z] /rayci/python/ray/_private/auto_init_hook.py:21: in auto_init_wrapper
  | [2025-05-21T17:20:28Z]     return fn(*args, **kwargs)
  | [2025-05-21T17:20:28Z] /rayci/python/ray/_private/client_mode_hook.py:103: in wrapper
  | [2025-05-21T17:20:28Z]     return func(*args, **kwargs)
  | [2025-05-21T17:20:28Z] /rayci/python/ray/_private/worker.py:2842: in get
  | [2025-05-21T17:20:28Z]     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  | [2025-05-21T17:20:28Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  | [2025-05-21T17:20:28Z]
  | [2025-05-21T17:20:28Z] self = <ray._private.worker.Worker object at 0x7ff6bcc8b220>
  | [2025-05-21T17:20:28Z] object_refs = [ObjectRef(00ffffffffffffffffffffffffffffffffffffff0100000002e1f505)]
  | [2025-05-21T17:20:28Z] timeout = None, return_exceptions = False, skip_deserialization = False
  | [2025-05-21T17:20:28Z]
  | [2025-05-21T17:20:28Z]     def get_objects(
  | [2025-05-21T17:20:28Z]         self,
  | [2025-05-21T17:20:28Z]         object_refs: list,
  | [2025-05-21T17:20:28Z]         timeout: Optional[float] = None,
  | [2025-05-21T17:20:28Z]         return_exceptions: bool = False,
  | [2025-05-21T17:20:28Z]         skip_deserialization: bool = False,
  | [2025-05-21T17:20:28Z]     ):
  | [2025-05-21T17:20:28Z]         """Get the values in the object store associated with the IDs.
  | [2025-05-21T17:20:28Z]
  | [2025-05-21T17:20:28Z]         Return the values from the local object store for object_refs. This
  | [2025-05-21T17:20:28Z]         will block until all the values for object_refs have been written to
  | [2025-05-21T17:20:28Z]         the local object store.
  | [2025-05-21T17:20:28Z]
  | [2025-05-21T17:20:28Z]         Args:
  | [2025-05-21T17:20:28Z]             object_refs: A list of the object refs
  | [2025-05-21T17:20:28Z]                 whose values should be retrieved.
  | [2025-05-21T17:20:28Z]             timeout: The maximum amount of time in
  | [2025-05-21T17:20:28Z]                 seconds to wait before returning.
  | [2025-05-21T17:20:28Z]             return_exceptions: If any of the objects deserialize to an
  | [2025-05-21T17:20:28Z]                 Exception object, whether to return them as values in the
  | [2025-05-21T17:20:28Z]                 returned list. If False, then the first found exception will be
  | [2025-05-21T17:20:28Z]                 raised.
  | [2025-05-21T17:20:28Z]             skip_deserialization: If true, only the buffer will be released and
  | [2025-05-21T17:20:28Z]                 the object associated with the buffer will not be deserialized.
  | [2025-05-21T17:20:28Z]         Returns:
  | [2025-05-21T17:20:28Z]             list: List of deserialized objects or None if skip_deserialization is True.
  | [2025-05-21T17:20:28Z]             bytes: UUID of the debugger breakpoint we should drop
  | [2025-05-21T17:20:28Z]                 into or b"" if there is no breakpoint.
  | [2025-05-21T17:20:28Z]         """
  | [2025-05-21T17:20:28Z]         # Make sure that the values are object refs.
  | [2025-05-21T17:20:28Z]         for object_ref in object_refs:
  | [2025-05-21T17:20:28Z]             if not isinstance(object_ref, ObjectRef):
  | [2025-05-21T17:20:28Z]                 raise TypeError(
  | [2025-05-21T17:20:28Z]                     f"Attempting to call `get` on the value {object_ref}, "
  | [2025-05-21T17:20:28Z]                     "which is not an ray.ObjectRef."
  | [2025-05-21T17:20:28Z]                 )
  | [2025-05-21T17:20:28Z]
  | [2025-05-21T17:20:28Z]         timeout_ms = (
  | [2025-05-21T17:20:28Z]             int(timeout * 1000) if timeout is not None and timeout != -1 else -1
  | [2025-05-21T17:20:28Z]         )
  | [2025-05-21T17:20:28Z]         data_metadata_pairs: List[
  | [2025-05-21T17:20:28Z]             Tuple[ray._raylet.Buffer, bytes]
  | [2025-05-21T17:20:28Z]         ] = self.core_worker.get_objects(
  | [2025-05-21T17:20:28Z]             object_refs,
  | [2025-05-21T17:20:28Z]             timeout_ms,
  | [2025-05-21T17:20:28Z]         )
  | [2025-05-21T17:20:28Z]
  | [2025-05-21T17:20:28Z]         debugger_breakpoint = b""
  | [2025-05-21T17:20:28Z]         for data, metadata in data_metadata_pairs:
  | [2025-05-21T17:20:28Z]             if metadata:
  | [2025-05-21T17:20:28Z]                 metadata_fields = metadata.split(b",")
  | [2025-05-21T17:20:28Z]                 if len(metadata_fields) >= 2 and metadata_fields[1].startswith(
  | [2025-05-21T17:20:28Z]                     ray_constants.OBJECT_METADATA_DEBUG_PREFIX
  | [2025-05-21T17:20:28Z]                 ):
  | [2025-05-21T17:20:28Z]                     debugger_breakpoint = metadata_fields[1][
  | [2025-05-21T17:20:28Z]                         len(ray_constants.OBJECT_METADATA_DEBUG_PREFIX) :
  | [2025-05-21T17:20:28Z]                     ]
  | [2025-05-21T17:20:28Z]         if skip_deserialization:
  | [2025-05-21T17:20:28Z]             return None, debugger_breakpoint
  | [2025-05-21T17:20:28Z]
  | [2025-05-21T17:20:28Z]         values = self.deserialize_objects(data_metadata_pairs, object_refs)
  | [2025-05-21T17:20:28Z]         if not return_exceptions:
  | [2025-05-21T17:20:28Z]             # Raise exceptions instead of returning them to the user.
  | [2025-05-21T17:20:28Z]             for i, value in enumerate(values):
  | [2025-05-21T17:20:28Z]                 if isinstance(value, RayError):
  | [2025-05-21T17:20:28Z]                     if isinstance(value, ray.exceptions.ObjectLostError):
  | [2025-05-21T17:20:28Z]                         global_worker.core_worker.dump_object_store_memory_usage()
  | [2025-05-21T17:20:28Z]                     if isinstance(value, RayTaskError):
  | [2025-05-21T17:20:28Z]                         raise value.as_instanceof_cause()
  | [2025-05-21T17:20:28Z]                     else:
  | [2025-05-21T17:20:28Z] >                       raise value
  | [2025-05-21T17:20:28Z] E                       ray.exceptions.RaySystemError: System error: module 'pyarrow' has no attribute 'PyExtensionType'
  | [2025-05-21T17:20:28Z] E                       traceback: Traceback (most recent call last):
  | [2025-05-21T17:20:28Z] E                         File "/rayci/python/ray/_private/serialization.py", line 460, in deserialize_objects
  | [2025-05-21T17:20:28Z] E                           obj = self._deserialize_object(data, metadata, object_ref)
  | [2025-05-21T17:20:28Z] E                         File "/rayci/python/ray/_private/serialization.py", line 317, in _deserialize_object
  | [2025-05-21T17:20:28Z] E                           return self._deserialize_msgpack_data(data, metadata_fields)
  | [2025-05-21T17:20:28Z] E                         File "/rayci/python/ray/_private/serialization.py", line 272, in _deserialize_msgpack_data
  | [2025-05-21T17:20:28Z] E                           python_objects = self._deserialize_pickle5_data(pickle5_data)
  | [2025-05-21T17:20:28Z] E                         File "/rayci/python/ray/_private/serialization.py", line 260, in _deserialize_pickle5_data
  | [2025-05-21T17:20:28Z] E                           obj = pickle.loads(in_band, buffers=buffers)
  | [2025-05-21T17:20:28Z] E                         File "/opt/miniconda/lib/python3.9/site-packages/daft/series.py", line 36, in from_arrow
  | [2025-05-21T17:20:28Z] E                           if DataType.from_arrow_type(array.type) == DataType.python():
  | [2025-05-21T17:20:28Z] E                         File "/opt/miniconda/lib/python3.9/site-packages/daft/datatype.py", line 457, in from_arrow_type
  | [2025-05-21T17:20:28Z] E                           elif isinstance(arrow_type, pa.PyExtensionType):
  | [2025-05-21T17:20:28Z] E                         File "/opt/miniconda/lib/python3.9/site-packages/daft/lazy_import.py", line 63, in __getattr__
  | [2025-05-21T17:20:28Z] E                           raise e
  | [2025-05-21T17:20:28Z] E                         File "/opt/miniconda/lib/python3.9/site-packages/daft/lazy_import.py", line 53, in __getattr__
  | [2025-05-21T17:20:28Z] E                           return getattr(self._load_module(), name)
  | [2025-05-21T17:20:28Z] E                       AttributeError: module 'pyarrow' has no attribute 'PyExtensionType'
  | [2025-05-21T17:20:28Z]
  | [2025-05-21T17:20:28Z] /rayci/python/ray/_private/worker.py:932: RaySystemError
  | [2025-05-21T17:20:28Z] ---------------------------- Captured stderr setup -----------------------------
  | [2025-05-21T17:20:28Z] 2025-05-21 17:19:46,973	WARNING services.py:2170 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 2684354560 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=4.60gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
  | [2025-05-21T17:20:28Z] 2025-05-21 17:19:47,112	INFO worker.py:1901 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265
  | [2025-05-21T17:20:28Z] ----------------------------- Captured stderr call -----------------------------
  | [2025-05-21T17:20:28Z] 2025-05-21 17:19:49,133	ERROR serialization.py:462 -- module 'pyarrow' has no attribute 'PyExtensionType'
  | [2025-05-21T17:20:28Z] Traceback (most recent call last):
  | [2025-05-21T17:20:28Z]   File "/rayci/python/ray/_private/serialization.py", line 460, in deserialize_objects
  | [2025-05-21T17:20:28Z]     obj = self._deserialize_object(data, metadata, object_ref)
  | [2025-05-21T17:20:28Z]   File "/rayci/python/ray/_private/serialization.py", line 317, in _deserialize_object
  | [2025-05-21T17:20:28Z]     return self._deserialize_msgpack_data(data, metadata_fields)
  | [2025-05-21T17:20:28Z]   File "/rayci/python/ray/_private/serialization.py", line 272, in _deserialize_msgpack_data
  | [2025-05-21T17:20:28Z]     python_objects = self._deserialize_pickle5_data(pickle5_data)
  | [2025-05-21T17:20:28Z]   File "/rayci/python/ray/_private/serialization.py", line 260, in _deserialize_pickle5_data
  | [2025-05-21T17:20:28Z]     obj = pickle.loads(in_band, buffers=buffers)
  | [2025-05-21T17:20:28Z]   File "/opt/miniconda/lib/python3.9/site-packages/daft/series.py", line 36, in from_arrow
  | [2025-05-21T17:20:28Z]     if DataType.from_arrow_type(array.type) == DataType.python():
  | [2025-05-21T17:20:28Z]   File "/opt/miniconda/lib/python3.9/site-packages/daft/datatype.py", line 457, in from_arrow_type
  | [2025-05-21T17:20:28Z]     elif isinstance(arrow_type, pa.PyExtensionType):
  | [2025-05-21T17:20:28Z]   File "/opt/miniconda/lib/python3.9/site-packages/daft/lazy_import.py", line 63, in __getattr__
  | [2025-05-21T17:20:28Z]     raise e
  | [2025-05-21T17:20:28Z]   File "/opt/miniconda/lib/python3.9/site-packages/daft/lazy_import.py", line 53, in __getattr__
  | [2025-05-21T17:20:28Z]     return getattr(self._load_module(), name)
  | [2025-05-21T17:20:28Z] AttributeError: module 'pyarrow' has no attribute 'PyExtensionType'
  | [2025-05-21T17:20:28Z] =========================== short test summary info ============================
  | [2025-05-21T17:20:28Z] FAILED python/ray/data/tests/test_daft.py::test_daft_round_trip - ray.excepti...
  | [2025-05-21T17:20:28Z] ============================== 1 failed in 10.92s ==============================
  | [2025-05-21T17:20:28Z] ================================================================================
  |  

```

## Related issue number

<!-- For example: "Closes #1234" -->
https://github.com/ray-project/ray/issues/53278

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git
commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for
https://docs.ray.io/en/master/.
- [ ] I've added any new APIs to the API Reference. For example, if I
added a
method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a
few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

---------

Signed-off-by: Srinath Krishnamachari <srinath.krishnamachari@anyscale.com>
Signed-off-by: Balaji Veeramani <bveeramani@berkeley.edu>
Co-authored-by: Balaji Veeramani <bveeramani@berkeley.edu>