[Error message] Improve the resource spec error message (#29842)
Fixes
1. memory / object store memory doesn't give correct error message.
2. The current error message is confusing. This makes the error message a bit more understandable. 

Example of ray start --head --resources={'GPU': 1000000000, 'CPU': 1}
```
AssertionError: {'GPU': 1000000000, 'CPU': 1} -> `CPU` cannot be a custom resource because it is one of the default resources ({'object_store_memory', 'CPU', 'memory', 'GPU'}). Use `num_cpus` instead. For example, use `ray start --num-cpus=1` instead of `ray start --resources={'CPU': 1}`
```


Signed-off-by: Shomil Jain <shomil@anyscale.com>