[core] Fallback unserializable exceptions to their string representation (#55476)
Falls back to printing the user exception's string representation
instead of simply throwing a generic (non debugable) ray internal
exception when the user's exception is not serializable.

eg for:
```python
import openai
import ray
from openai import AuthenticationError

def call_openai_and_error_out():
    client = openai.OpenAI(
        base_url="https://api.endpoints.anyscale.com/v1",
        api_key="test",
    )
    try:
        client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a chatbot."},
                {"role": "user", "content": "What is the capital of France?"},
            ],
        )
    except AuthenticationError as e:
        print("Errored as expected given API key is invalid.")
        raise e

remote_fn = ray.remote(call_openai_and_error_out)
ray.get(remote_fn.remote())
```

we previously threw

```
2025-08-02 14:19:36,726 ERROR serialization.py:462 -- Failed to unpickle serialized exception
Traceback (most recent call last):
  File "/Users/rliaw/miniconda3/lib/python3.10/site-packages/ray/exceptions.py", line 51, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rliaw/miniconda3/lib/python3.10/site-packages/ray/_private/serialization.py", line 460, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/Users/rliaw/miniconda3/lib/python3.10/site-packages/ray/_private/serialization.py", line 342, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/Users/rliaw/miniconda3/lib/python3.10/site-packages/ray/exceptions.py", line 45, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/Users/rliaw/miniconda3/lib/python3.10/site-packages/ray/exceptions.py", line 54, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
Traceback (most recent call last):
  File "/Users/rliaw/dev/proteins/_test.py", line 31, in <module>
    ray.get(remote_fn.remote())
  File "/Users/rliaw/miniconda3/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/Users/rliaw/miniconda3/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/rliaw/miniconda3/lib/python3.10/site-packages/ray/_private/worker.py", line 2782, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/Users/rliaw/miniconda3/lib/python3.10/site-packages/ray/_private/worker.py", line 931, in get_objects
    raise value
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
traceback: Traceback (most recent call last):
  File "/Users/rliaw/miniconda3/lib/python3.10/site-packages/ray/exceptions.py", line 51, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rliaw/miniconda3/lib/python3.10/site-packages/ray/_private/serialization.py", line 460, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/Users/rliaw/miniconda3/lib/python3.10/site-packages/ray/_private/serialization.py", line 342, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/Users/rliaw/miniconda3/lib/python3.10/site-packages/ray/exceptions.py", line 45, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/Users/rliaw/miniconda3/lib/python3.10/site-packages/ray/exceptions.py", line 54, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
```

but with this change we instead throw:

```
ERROR serialization.py:539 -- Failed to unpickle serialized exception
Original exception (string repr):
ray.exceptions.RayTaskError: ray::call_openai_and_error_out() (pid=2177610, ip=172.31.5.49)
    exc_info=True)
  File "/home/ubuntu/clone/ray/test.py", line 12, in call_openai_and_error_out
    client.chat.completions.create(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_utils/_utils.py", line 287, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/resources/chat/completions/completions.py", line 925, in create
    return self._post(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_base_client.py", line 1249, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_base_client.py", line 1037, in request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: <html lang="en">
<head></head>
<meta charset="UTF-8">
        <p>Thank you for using Anyscale's Public Endpoints API.</p>
        <p>Effective August 1, 2024 Anyscale Endpoints API is available exclusively through the fully Hosted Anyscale Platform. Multi-tenant access to LLM models has been removed.</p><p>With the Hosted Anyscale Platform, you can access the latest GPUs billed by <a href="https://www.anyscale.com/pricing">the second</a>, and deploy models on your own dedicated instances. Enjoy full customization to build your end-to-end applications with Anyscale. <a href="https://console.anyscale.com/register/ha">Get started</a> today.</p>
</body>
</html>
Traceback (most recent call last):
  File "/home/ubuntu/clone/ray/python/ray/exceptions.py", line 50, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: __init__() missing 2 required keyword-only arguments: 'response' and 'body'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/clone/ray/python/ray/_private/serialization.py", line 532, in deserialize_objects
    obj = self._deserialize_object(
  File "/home/ubuntu/clone/ray/python/ray/_private/serialization.py", line 396, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/home/ubuntu/clone/ray/python/ray/exceptions.py", line 44, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/home/ubuntu/clone/ray/python/ray/exceptions.py", line 60, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
Original exception (string repr):
ray.exceptions.RayTaskError: ray::call_openai_and_error_out() (pid=2177610, ip=172.31.5.49)
    exc_info=True)
  File "/home/ubuntu/clone/ray/test.py", line 12, in call_openai_and_error_out
    client.chat.completions.create(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_utils/_utils.py", line 287, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/resources/chat/completions/completions.py", line 925, in create
    return self._post(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_base_client.py", line 1249, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_base_client.py", line 1037, in request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: <html lang="en">
<head></head>
<meta charset="UTF-8">
        <p>Thank you for using Anyscale's Public Endpoints API.</p>
        <p>Effective August 1, 2024 Anyscale Endpoints API is available exclusively through the fully Hosted Anyscale Platform. Multi-tenant access to LLM models has been removed.</p><p>With the Hosted Anyscale Platform, you can access the latest GPUs billed by <a href="https://www.anyscale.com/pricing">the second</a>, and deploy models on your own dedicated instances. Enjoy full customization to build your end-to-end applications with Anyscale. <a href="https://console.anyscale.com/register/ha">Get started</a> today.</p>
</body>
</html>

Traceback (most recent call last):
  File "/home/ubuntu/clone/ray/test.py", line 24, in <module>
    ray.get(remote_fn.remote())
  File "/home/ubuntu/clone/ray/python/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/clone/ray/python/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/clone/ray/python/ray/_private/worker.py", line 2869, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/ubuntu/clone/ray/python/ray/_private/worker.py", line 970, in get_objects
    raise value
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
Original exception (string repr):
ray.exceptions.RayTaskError: ray::call_openai_and_error_out() (pid=2177610, ip=172.31.5.49)
    exc_info=True)
  File "/home/ubuntu/clone/ray/test.py", line 12, in call_openai_and_error_out
    client.chat.completions.create(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_utils/_utils.py", line 287, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/resources/chat/completions/completions.py", line 925, in create
    return self._post(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_base_client.py", line 1249, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_base_client.py", line 1037, in request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: <html lang="en">
<head></head>
<meta charset="UTF-8">
        <p>Thank you for using Anyscale's Public Endpoints API.</p>
        <p>Effective August 1, 2024 Anyscale Endpoints API is available exclusively through the fully Hosted Anyscale Platform. Multi-tenant access to LLM models has been removed.</p><p>With the Hosted Anyscale Platform, you can access the latest GPUs billed by <a href="https://www.anyscale.com/pricing">the second</a>, and deploy models on your own dedicated instances. Enjoy full customization to build your end-to-end applications with Anyscale. <a href="https://console.anyscale.com/register/ha">Get started</a> today.</p>
</body>
</html>

traceback: Traceback (most recent call last):
  File "/home/ubuntu/clone/ray/python/ray/exceptions.py", line 50, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: __init__() missing 2 required keyword-only arguments: 'response' and 'body'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/clone/ray/python/ray/_private/serialization.py", line 532, in deserialize_objects
    obj = self._deserialize_object(
  File "/home/ubuntu/clone/ray/python/ray/_private/serialization.py", line 396, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/home/ubuntu/clone/ray/python/ray/exceptions.py", line 44, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/home/ubuntu/clone/ray/python/ray/exceptions.py", line 60, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
Original exception (string repr):
ray.exceptions.RayTaskError: ray::call_openai_and_error_out() (pid=2177610, ip=172.31.5.49)
    exc_info=True)
  File "/home/ubuntu/clone/ray/test.py", line 12, in call_openai_and_error_out
    client.chat.completions.create(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_utils/_utils.py", line 287, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/resources/chat/completions/completions.py", line 925, in create
    return self._post(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_base_client.py", line 1249, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_base_client.py", line 1037, in request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: <html lang="en">
<head></head>
<meta charset="UTF-8">
        <p>Thank you for using Anyscale's Public Endpoints API.</p>
        <p>Effective August 1, 2024 Anyscale Endpoints API is available exclusively through the fully Hosted Anyscale Platform. Multi-tenant access to LLM models has been removed.</p><p>With the Hosted Anyscale Platform, you can access the latest GPUs billed by <a href="https://www.anyscale.com/pricing">the second</a>, and deploy models on your own dedicated instances. Enjoy full customization to build your end-to-end applications with Anyscale. <a href="https://console.anyscale.com/register/ha">Get started</a> today.</p>
</body>
</html>
```

## Related issue number
https://github.com/ray-project/ray/issues/55171
https://github.com/ray-project/ray/issues/43428
https://github.com/ray-project/ray/issues/50138
https://github.com/ray-project/ray/issues/49885
https://github.com/ray-project/ray/issues/49970
https://github.com/ray-project/ray/issues/54341

---------

Signed-off-by: sampan <sampan@anyscale.com>
Co-authored-by: sampan <sampan@anyscale.com>
Signed-off-by: Andrew Grosser <dioptre@gmail.com>