[Serve] Call shared long poll client router registration in event loop (#53613)
## Why are these changes needed?

We found a second bug with the shared long poll client, similar to
https://github.com/ray-project/ray/pull/52793 - this time it's for a
different part of the registration process. The error we saw looked
like:
```
 2025-06-06 14:29:14 ERROR Exception in callback LongPollClient._process_update.<locals>.chained() at /app/virtualenv/lib64/python3.12/site-packages/ray/serve/_private/long_poll.py:215
 handle: <Handle LongPollClient._process_update.<locals>.chained() at /app/virtualenv/lib64/python3.12/site-packages/ray/serve/_private/long_poll.py:215>
 Traceback (most recent call last):
   File "/usr/lib64/python3.12/asyncio/events.py", line 88, in _run
     self._context.run(self._callback, *self._args)
   File "/app/virtualenv/lib64/python3.12/site-packages/ray/serve/_private/long_poll.py", line 216, in chained
     callback(arg)
   File "/app/virtualenv/lib64/python3.12/site-packages/ray/serve/_private/router.py", line 833, in update_deployment_config
     for router in self.routers[deployment_id]:
                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^
   File "/usr/lib64/python3.12/_weakrefset.py", line 65, in __iter__
     for itemref in self.data:
                    ^^^^^^^^^
 RuntimeError: Set changed size during iteration
```

This is getting pretty gnarly. I feel like there's a potential future
refactor of the long poll client code that makes it truly `async` so
that we don't need to worry about this stuff? But I'm not too familiar
with how/why the background threads are being used here.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git
commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for
https://docs.ray.io/en/master/.
- [ ] I've added any new APIs to the API Reference. For example, if I
added a
method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a
few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

---------

Signed-off-by: Josh Karpel <josh.karpel@gmail.com>
Signed-off-by: elliot-barn <elliot.barnwell@anyscale.com>