[ci] Fix dask Ray client tests (#35233)
The Ray client tests for dask are broken in master:

```
ModuleNotFoundError: No module named 'dask'
```

We didn't change any logic in our CI, but it seems we never explicitly installed dask in the respective job. Maybe it was previously automatically installed by some subdependency.

This PR adds the data processing requirements to the job, thus explicitly installing dask.

Signed-off-by: Kai Fricke <kai@anyscale.com>