[Data] Clarify schema validation error (#48882)
```python
ray.data.range(1).groupby("does_not_exist").count().materialize()
```

**Before**
```
ValueError: The column 'does_not_exist' does not exist in the schema 'Column  Type
------  ----
id      int64'.
```

**After**
```
ValueError: You specified the column 'does_not_exist', but there's no such column in the dataset. The dataset has columns: {'id'}
```

---------

Signed-off-by: Balaji Veeramani <bveeramani@berkeley.edu>