[air/output] Fix output encoding in windows (#35770)
When tune runs in a windows session with legacy encoding (e.g. cp-1252), the characters in the new output will result in an encoding error:

```
  File "c:\install\ray\python\ray\tune\experimental\output.py", line 700, in experiment_started
    print(
  File "C:\Miniconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-72: character maps to <undefined>
```

This PR detects a non-utf encoding and reverts to ascii characters which are fully compatible with windows. This is equivalent to the old Tune output format:

```
+------------------------------+----------+-------+
| Trial name                   | status   | loc   |
|------------------------------+----------+-------|
| LightningTrainer_47320_00000 | PENDING  |       |
+------------------------------+----------+-------+
```

The PR also adds a small fix in tune controller that came up when debugging this issue on windows.

Signed-off-by: Kai Fricke <kai@anyscale.com>
Signed-off-by: e428265 <arvind.chandramouli@lmco.com>