[serve] deflake test autoscaling policy (#46910)
<!-- Thank you for your contribution! Please review
https://github.com/ray-project/ray/blob/master/CONTRIBUTING.rst before
opening a pull request. -->

<!-- Please add a reviewer to the assignee section when you create a PR.
If you don't have the access to it, we will shortly find a reviewer and
assign them to your PR. -->

## Why are these changes needed?

Fixes 2 issues:
1. `test_autoscaling_policy.py` as a whole errors out at the end when
serve shuts down because routers are still sending metrics to a
non-existent controller. Fix: add a flag to router metrics manager which
is flipped to true when the handle shuts down, and avoid restarting the
metrics pusher when a new deployment config is received.
```
2024-07-31 15:33:25,312 ERROR metrics_utils.py:67 -- Failed to run metrics task 'push_metrics_to_controller': Failed to submit task to actor ActorID(2e92d7b291cad0477744ff7f01000000) due to b"Can't find actor 2e92d7b291cad0477744ff7f01000000. It
 might be dead or it's from a different cluster"
Traceback (most recent call last):
  File "/Users/cindyz/ray/python/ray/serve/_private/metrics_utils.py", line 65, in metrics_task
    self._tasks[name].task_func()
  File "/Users/cindyz/ray/python/ray/serve/_private/router.py", line 260, in push_autoscaling_metrics_to_controller
    self._controller_handle.record_handle_metrics.remote(
  File "/Users/cindyz/ray/python/ray/actor.py", line 202, in remote
    return self._remote(args, kwargs)
  File "/Users/cindyz/ray/python/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/Users/cindyz/ray/python/ray/util/tracing/tracing_helper.py", line 426, in _start_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/Users/cindyz/ray/python/ray/actor.py", line 330, in _remote
    return invocation(args, kwargs)
  File "/Users/cindyz/ray/python/ray/actor.py", line 311, in invocation
    return actor._actor_method_call(
  File "/Users/cindyz/ray/python/ray/actor.py", line 1460, in _actor_method_call
    object_refs = worker.core_worker.submit_actor_task(
  File "python/ray/_raylet.pyx", line 4261, in ray._raylet.CoreWorker.submit_actor_task
    with self.profile_event(b"submit_task"):
  File "python/ray/_raylet.pyx", line 4316, in ray._raylet.CoreWorker.submit_actor_task
    raise Exception(f"Failed to submit task to actor {actor_id} "
Exception: Failed to submit task to actor ActorID(2e92d7b291cad0477744ff7f01000000) due to b"Can't find actor 2e92d7b291cad0477744ff7f01000000. It might be dead or it's from a different cluster"
```

2. The autoscaling test `test_e2e_preserve_prev_replicas_rest_api` has
been failing because the script is fetching the wrong signal actor.
```
(ServeReplica:default:g pid=77537) ERROR 2024-07-31 16:15:01,331 default_g jlrji5zh 3c52d6cd-2a58-437a-85e3-32c057c19cb1 / replica.py:359 - Request failed:
(ServeReplica:default:g pid=77537) ray::ServeReplica:default:g.handle_request_with_rejection() (pid=77537, ip=127.0.0.1)
(ServeReplica:default:g pid=77537)   File "/Users/cindyz/ray/python/ray/serve/_private/utils.py", line 168, in wrap_to_ray_error
(ServeReplica:default:g pid=77537)     raise exception
(ServeReplica:default:g pid=77537)   File "/Users/cindyz/ray/python/ray/serve/_private/replica.py", line 1145, in call_user_method
(ServeReplica:default:g pid=77537)     await self._call_func_or_gen(
(ServeReplica:default:g pid=77537)   File "/Users/cindyz/ray/python/ray/serve/_private/replica.py", line 867, in _call_func_or_gen
(ServeReplica:default:g pid=77537)     result = callable(*args, **kwargs)
(ServeReplica:default:g pid=77537)   File "/tmp/ray/session_2024-07-31_16-14-54_658215_77498/runtime_resources/working_dir_files/file__var_folders_sf__p13kld96r76l9lbf6pzddfm0000gn_T_tmpb9j_l0qq/app.py", line 8, in g
(ServeReplica:default:g pid=77537)     signal = ray.get_actor("signal", namespace="serve")
(ServeReplica:default:g pid=77537)   File "python/ray/includes/common.pxi", line 83, in ray._raylet.check_status
(ServeReplica:default:g pid=77537) ValueError: Failed to look up actor with name 'signal'. This could because 1. You are trying to look up a named actor you didn't create. 2. The named actor died. 3. You did not use a namespace matching the name
space of the actor.
```

## Related issue number

<!-- For example: "Closes #1234" -->

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git
commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for
https://docs.ray.io/en/master/.
- [ ] I've added any new APIs to the API Reference. For example, if I
added a
method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a
few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

Signed-off-by: Cindy Zhang <cindyzyx9@gmail.com>