Fix triton server doc (#52665)
## Why are these changes needed?
The model referenced in the readme cannot be located anymore:
```
OSError: Can't load config for 'CompVis/stable-diffusion-v1-4'.
If you were trying to load it from 'https://huggingface.co/models',
make sure you don't have a local directory with the same name. 

Otherwise, make sure 'CompVis/stable-diffusion-v1-4' is the correct path to a 
directory containing a config.json file
```
Updated to use the `StableDiffusionPipe` for cleaner sub-model
compilation step.

Also added a short comment on ensuring accessibility to the artifacts
for worker nodes in distributed environment.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git
commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for
https://docs.ray.io/en/master/.
- [ ] I've added any new APIs to the API Reference. For example, if I
added a
method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a
few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

---------

Signed-off-by: Omkar Kulkarni <omkar@omkar-JKJHCX74L6.local>
Signed-off-by: Omkar Kulkarni <omkar@anyscale.com>
Signed-off-by: ok-scale <omkar@anyscale.com>
Co-authored-by: Omkar Kulkarni <omkar@omkar-JKJHCX74L6.local>
Co-authored-by: akshay-anyscale <122416226+akshay-anyscale@users.noreply.github.com>
Co-authored-by: Cindy Zhang <cindyzyx9@gmail.com>