[ci][llm] Fix release tests' incompatibility with Ansycale SDK (#63134)
`anyscale` is pinned to `0.26.97` on the `llm-cu130` image. In this
version, `anyscale.job.status()` fetches job runs through a new internal
endpoint (`POST /api/v2/decorated_ha_jobs/job_runs/search`) which
requires an API key, but the release test is running inside an Anyscale
job with only the cluster CLI token. This results in the following error
([sample
log](https://console.anyscale-staging.com/cld_wy5a6nhazplvu32526ams61d98/prj_lhlrf1u5yv8qz9qg3xzw8fkiiq/jobs/prodjob_rcgpimwr11kgmr6t3w3cr6rpdn?job-logs-section-tabs=application_logs&job-tab=overview)).
```
ValueError: The endpoint POST /api/v2/decorated_ha_jobs/job_runs/search requires a different
type of authentication, please use your API key instead of the cluster CLI token.
```

Signed-off-by: Jeffrey Wang <jeffreywang@anyscale.com>