[Serve] [CI] Fix micro_benchmark by making --http-test a flag which requires no argument (#29012)
Fixes the error https://buildkite.com/ray-project/release-tests-branch/builds/1080#0183906e-88ac-4847-bb0d-93a869a22be1/724-727

Error: Option '--http-test' requires an argument.