Fix special characters naming for serve (#52702)
## Why are these changes needed?
When creating a Serve deployment with a name containing a slash (such as
`TextGenerationModel.options(name="huawei-noah/TinyBERT_General_4L_312D")`)
leads to actor failures. The error occurs because the slash in the name
is likely being used as a path separator in log files.

Error: `FileNotFoundError: [Errno 2] No such file or directory:
'/tmp/ray/session_2025-03-11_16-02-48_264712_45753/logs/serve/replica_default_huawei-noah/TinyBERT_General_4L_312D_eo3vqu7d.log'`


In general, any other special character used may cause the logger to
crash. This branch fixes the issue by replacing all special characters
with `_` for logging purposes.


## Related issue number
https://github.com/ray-project/ray/issues/51280

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git
commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for
https://docs.ray.io/en/master/.
- [ ] I've added any new APIs to the API Reference. For example, if I
added a
method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a
few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

---------

Signed-off-by: Omkar Kulkarni <omkar@omkar-JKJHCX74L6.local>
Signed-off-by: Omkar Kulkarni <omkar@anyscale.com>
Co-authored-by: Omkar Kulkarni <omkar@omkar-JKJHCX74L6.local>