[train][release] Get correct dreambooth requirements.txt (#62525)
# Summary

This PR fixes pip jax dependency issues in our dreambooth release test.
Original error:

```

Collecting jax==0.4.13 (from -r dreambooth/requirements.txt (line 7))
--
Downloading jax-0.4.13.tar.gz (1.3 MB)
ââââââââââââââââââââââââââââââââââââââââ 1.3/1.3 MB 59.5 MB/s eta 0:00:00
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'done'
ERROR: Ignored the following yanked versions: 0.4.32
ERROR: Ignored the following versions that require a different python version: 0.11.0 Requires-Python >=3.11; 0.11.1 Requires-Python >=3.11; 0.11.2 Requires-Python >=3.11; 0.12.0 Requires-Python >=3.11; 0.12.1 Requires-Python >=3.11; 0.12.2 Requires-Python >=3.11; 0.12.3 Requires-Python >=3.11; 0.12.4 Requires-Python >=3.11; 0.12.5 Requires-Python >=3.11; 0.12.6 Requires-Python >=3.11; 0.7.0 Requires-Python >=3.11; 0.7.1 Requires-Python >=3.11; 0.7.2 Requires-Python >=3.11; 0.8.0 Requires-Python >=3.11; 0.8.1 Requires-Python >=3.11; 0.8.2 Requires-Python >=3.11; 0.8.3 Requires-Python >=3.11; 0.9.0 Requires-Python >=3.11; 0.9.0.1 Requires-Python >=3.11; 0.9.1 Requires-Python >=3.11; 0.9.2 Requires-Python >=3.11
ERROR: Could not find a version that satisfies the requirement jaxlib==0.4.13 (from versions: 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30, 0.4.31, 0.4.33, 0.4.34, 0.4.35, 0.4.36, 0.4.38, 0.5.0, 0.5.1, 0.5.3, 0.6.0, 0.6.1, 0.6.2)
ERROR: No matching distribution found for jaxlib==0.4.13
Subprocess return code: 1
```

I did the following:
1) Created new python3.9 conda env
2) Ran `pip-compile
release/air_examples/dreambooth/dreambooth/requirements.txt
--output-file=requirements.test.txt`. This indeed failed with
`pip._internal.exceptions.DistributionNotFound: No matching distribution
found for jaxlib==0.4.13`
3) Relaxed the `jax`, `jaxlib` and `flax` requirements in
requirements.txt
4) Ran `pip-compile
release/air_examples/dreambooth/dreambooth/requirements.txt
--output-file=requirements.test.txt` again. Here is the result:
https://gist.github.com/TimothySeah/5a5e345d581d0b7f97162a4e3a494edb
5) Copied the `jax`, `jaxlib`, and `flax` versions back to
`requirements.txt`

But then that resulted in some dependency issues still:
https://buildkite.com/ray-project/release/builds/88314#019d7a74-9760-4595-b080-72d0797c2f4b
i.e. `
ImportError: cannot import name 'cached_download' from
'huggingface_hub'`

I repeated the process above but unpinned all the deps this time, which
produced this file:
https://gist.github.com/TimothySeah/58f928b7d1d611b5ff88d383934e2b5f. I
then updated requirements.txt to match. But that was even worse:
https://buildkite.com/ray-project/release/builds/88650#019d8961-6343-420f-a3cc-dbb33786b18f.

I went back to the first change but only downgraded huggingface_hub to a
version that contains `cached_download`. Now there's a version mismatch
between diffusers and jax:
https://buildkite.com/ray-project/release/builds/88671#019d899f-1699-4e39-8b10-9b38effda088

Taking a step back, I see that the `from versions` log mentions jax
0.4.17 onwards, implying that jax 0.4.13 is no longer supported on my
python/cuda setup. Therefore I tried changing it to jax 0.4.17, which
produced this requirements file:
https://gist.github.com/TimothySeah/465b0b09d46531216fbd9162a183738e.
Back to the cached_download error:
https://buildkite.com/ray-project/release/builds/88884#019d8e89-b998-48b1-8d8d-7761de4ca484.

Now I'm trying an older `huggingface_hub` that supports
`cached_download`.



# Testing

Release tests with `name:air_example_dreambooth_finetuning.*`

---------

Signed-off-by: Timothy Seah <tseah@anyscale.com>