[Serve] Fix Stable Diffusion example (#36525)
I tried to deploy the Stable Diffusion example with KubeRay on EKS, and I hit the following bugs.

The latest release of diffusers (v0.17.1) is not compatible with the default transformers==4.19.1 installed in the ray-ml image. To address this, we need to specify a compatible version of diffusers. You can find more details about this issue at  cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils' CompVis/stable-diffusion#627 (note that this is not the exact repository we are using, but it shares a similar issue). The error message is displayed in the following figure.
Screen Shot 2023-06-16 at 3 27 55 PM

After installing the correct version of diffusers, I encountered an issue described in this discussion where I received a "RuntimeError: expected scalar type Half but found Float". To resolve this, I needed to use torch.autocast("cuda") to enable mixed precision execution. The error message is displayed in the following figure.
Screen Shot 2023-06-16 at 3 25 54 PM

After implementing these two changes, everything is functioning correctly.

Signed-off-by: Bhavpreet Singh <singh.bhavpreet00@gmail.com>