[docs] ray.remote(object_store_memory) is for actors only (#26161)
We explicitely disallow scheduling tasks based on object store memory, so we should state that in the docs

cc @scottsun94 

```
>>> import ray
>>> @ray.remote(object_store_memory=100)
... def foo():
...  pass
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alex/anyscale/ray/python/ray/worker.py", line 2479, in _make_remote
    ray_option_utils.validate_task_options(options, in_options=False)
  File "/Users/alex/anyscale/ray/python/ray/_private/ray_option_utils.py", line 191, in validate_task_options
    task_options[k].validate(k, v)
  File "/Users/alex/anyscale/ray/python/ray/_private/ray_option_utils.py", line 33, in validate
    raise ValueError(self.error_message_for_value_constraint)
ValueError: Setting 'object_store_memory' is not implemented for tasks
```

Co-authored-by: Alex Wu <alex@anyscale.com>
Signed-off-by: Shomil Jain <shomil@anyscale.com>