[cluster launcher] Deflake AWS cluster launcher test by adding retries (#33774)
Adds sleeps and retries for running ray.init(address=...) after running ray up.

Adds sleeps and retries for running ray.init(address=...) after running ray up.

Sometimes, running ray.init(address=...) after ray up can cause the following error:

======================================
Verifying Ray is running...
2023-03-23 16:37:32,048 INFO util.py:372 -- setting max workers for head node type to 0
2023-03-23 23:37:33,670 INFO worker.py:1413 -- Connecting to existing Ray cluster at address: 10.0.3.62:6379...
[2023-03-23 23:37:33,677 W 3123 3123] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-03-23 23:37:34,678 W 3123 3123] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-03-23 23:37:35,679 W 3123 3123] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-03-23 23:37:36,680 W 3123 3123] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-03-23 23:37:37,681 W 3123 3123] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-03-23 23:37:38,681 W 3123 3123] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-03-23 23:37:39,682 W 3123 3123] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-03-23 23:37:40,683 W 3123 3123] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-03-23 23:37:41,684 W 3123 3123] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2023-03-23 23:37:42,685 W 3123 3123] global_state_accessor.cc:389: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/worker.py", line 1566, in init
    _global_node = ray._private.node.Node(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/node.py", line 244, in __init__
    node_info = ray._private.services.get_node_to_connect_for_driver(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/services.py", line 472, in get_node_to_connect_for_driver
    return global_state.get_node_to_connect_for_driver(node_ip_address)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/state.py", line 752, in get_node_to_connect_for_driver
    node_info_str = self.global_state_accessor.get_node_to_connect_for_driver(
  File "python/ray/includes/global_state_accessor.pxi", line 156, in ray._raylet.GlobalStateAccessor.get_node_to_connect_for_driver
RuntimeError: b'GCS has started but no raylets have registered yet.'
In this PR, we add a 5 second sleep and retries to hopefully give more time for Raylets to register.

Signed-off-by: elliottower <elliot@elliottower.com>