[data] Handle errors in SplitCoordinator when generating a new epoch (#47176)
## Why are these changes needed?

Previously if an error happens while launching the executor while
generating a new epoch, we don't handle the error properly, thus users
will get a confusing error. And the actual root cause will be hidden.

```
E                         File "/Users/chenh/code/ray/python/ray/data/_internal/iterator/stream_split_iterator.py", line 197, in start_epoch
E                           epoch_id = self._barrier(split_idx)
E                         File "/Users/chenh/code/ray/python/ray/data/_internal/iterator/stream_split_iterator.py", line 285, in _barrier
E                           assert self._output_iterator is not None
E                       AssertionError
```

This PR solves this issue by storing the error and re-raise it from all
threads.


## Related issue number

Closes https://github.com/ray-project/ray/issues/45225

---------

Signed-off-by: Hao Chen <chenh1024@gmail.com>