Fix macOS compilation
https://buildkite.com/ray-project/ray-builders-branch/builds/1802#d42a0e6c-ff64-4c31-acb3-320d73c66ef4/629-805
```
src/ray/core_worker/reference_count_test.cc:280:23: error: loop variable 'callback_it' creates a copy from type 'const std::__1::pair<const ray::ObjectID, std::__1::function<void ()>>' [-Werror,-Wrange-loop-construct]
      for (const auto callback_it : callback_map) {
                      ^
src/ray/core_worker/reference_count_test.cc:280:12: note: use reference type 'const std::__1::pair<const ray::ObjectID, std::__1::function<void ()>> &' to prevent copying
      for (const auto callback_it : callback_map) {
           ^~~~~~~~~~~~~~~~~~~~~~~~
                      &
src/ray/core_worker/reference_count_test.cc:278:21: error: loop variable 'it' creates a copy from type 'const std::__1::pair<const std::__1::basic_string<char>, std::__1::unordered_map<ray::ObjectID, std::__1::function<void ()>>>' [-Werror,-Wrange-loop-construct]
    for (const auto it : subscription_failure_callback_map) {
                    ^
src/ray/core_worker/reference_count_test.cc:278:10: note: use reference type 'const std::__1::pair<const std::__1::basic_string<char>, std::__1::unordered_map<ray::ObjectID, std::__1::function<void ()>>> &' to prevent copying
    for (const auto it : subscription_failure_callback_map) {
         ^~~~~~~~~~~~~~~
                    &
```

This was not detected because two commits were merged right after each
other and we don't linearize merges. So the buildkite PR was green, and
the OBOD PR was green as well.