[core] Add node_id validation in NodeAffinitySchedulingStrategy (#56708)
passing an invalid node_id to `NodeAffinitySchedulingStrategy` leads to
a `RAY_CHECK(!node_id.IsNil())` failure, which is treated as `an
unexpected system state`. This pr adds validations to catch this issue
and throw a more user friendly error message.

code to repro:
```python
import ray

@ray.remote
def f():
    pass

ray.get(f.options(scheduling_strategy=ray.util.scheduling_strategies.NodeAffinitySchedulingStrategy(node_id="foobar", soft=True)).remote())
```

error message we threw previously:
```
[2025-09-15 09:28:36,668 E 10514 114390748] id.h:461: incorrect h
ex string length: 2 * 28 != 6, hex string: foobar
[2025-09-15 09:28:36,859 C 10514 114391697] accessor.cc:670:  An
unexpected system state has occurred. You have likely discovered
a bug in Ray. Please report this issue at https://github.com/ray-
project/ray/issues and we'll work with you to fix it. Check faile
d: !node_id.IsNil()
```

error message we throw (this pr)

```
ValueError: Invalid node_id 'foobar'. Node ID must be a valid hex string. To get a list of all nodes and their IDs in your cluster, use ray.nodes() refer to learn more https://docs.ray.io/en/latest/ray-core/miscellaneous.html#node-information
```

---------

Signed-off-by: sampan <sampan@anyscale.com>
Co-authored-by: Jiajun Yao <jeromeyjj@gmail.com>