[core] Introduce new exception type for un-pickleable exceptions  (#55878)
This PR introduces a new exception type `UnpickleableException` for
cases where the RayTaskException is not unpickleable.

previously we threw a `RaySystemError` with the original stacktrace
(string representation), but this is not right as the exception is not
really due to an issue internal to Ray.
<!-- Please give a short summary of the change and the problem this
solves. -->

sample code:
```python
import os
os.environ["RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO"] = "0"

import openai
import ray
from openai import AuthenticationError


def call_openai_and_error_out():
    client = openai.OpenAI(
        base_url="https://api.endpoints.anyscale.com/v1",
        api_key="test",
    )
    try:
        client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a chatbot."},
                {"role": "user", "content": "What is the capital of France?"},
            ],
        )
    except AuthenticationError as e:
        print("Errored as expected given API key is invalid.")
        raise e

remote_fn = ray.remote(call_openai_and_error_out)

ray.get(remote_fn.remote())
```

exception message:
```python
(base) ubuntu@devbox:~/clone/ray$ python test.py
2025-08-25 08:24:40,371 INFO worker.py:1939 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
Traceback (most recent call last):
  File "/home/ubuntu/clone/ray/test.py", line 28, in <module>
    ray.get(remote_fn.remote())
  File "/home/ubuntu/clone/ray/python/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/clone/ray/python/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/clone/ray/python/ray/_private/worker.py", line 2894, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/ubuntu/clone/ray/python/ray/_private/worker.py", line 967, in get_objects
    raise value
ray.exceptions.UnserializableException: Failed to deserialize exception. This typically occurs when the original exception class is not available, there are version incompatibilities, or the serialized data is corrupted.

Original exception:
ray.exceptions.RayTaskError: ray::call_openai_and_error_out() (pid=1996227, ip=172.31.5.49)
  File "/home/ubuntu/clone/ray/test.py", line 15, in call_openai_and_error_out
    client.chat.completions.create(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_utils/_utils.py", line 287, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/resources/chat/completions/completions.py", line 925, in create
    return self._post(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_base_client.py", line 1249, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/ubuntu/.local/lib/python3.9/site-packages/openai/_base_client.py", line 1037, in request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: <html lang="en">
<head></head>
<meta charset="UTF-8">
        <p>Thank you for using Anyscale's Public Endpoints API.</p>
        <p>Effective August 1, 2024 Anyscale Endpoints API is available exclusively through the fully Hosted Anyscale Platform. Multi-tenant access to LLM models has been removed.</p><p>With the Hosted Anyscale Platform, you can access the latest GPUs billed by <a href="https://www.anyscale.com/pricing">the second</a>, and deploy models on your own dedicated instances. Enjoy full customization to build your end-to-end applications with Anyscale. <a href="https://console.anyscale.com/register/ha">Get started</a> today.</p>
</body>
</html>
```

---------

Signed-off-by: sampan <sampan@anyscale.com>
Co-authored-by: Edward Oakes <ed.nmi.oakes@gmail.com>