[Data] Allow automatic handling of string features as byte features during TFRecord serialization (#37995)
I am attempting to use ray.data.write_tfrecords to convert my features into TFRecords. Since some of my features are string features, the following error is thrown:

ValueError: Value is of type string, which we cannot convert to a supported tf.train.Feature storage type (bytes, float, or int).
Naturally, TFRecords serializes string features as bytes feature automatically (as typically done in Tensorflow and Tensorflow-extended (TFX); see for example: https://github.com/tensorflow/tfx/blob/fd070288ffa5dcb28204810d2bed261c7e1df201/tfx/components/example_gen/csv_example_gen/executor.py#L67). Making the TFRecord writer automatically treat strings as bytes would help serialize string features correctly, avoiding the hassle of creating additional map functions to convert string features into bytes.

When reading TFRecords, however, we should still keep the bytes features as bytes, as the program does not necessarily know a byte object represents a string. In this example provided by Tensorflow, tensors are serialized into bytes and stored in tfrecords, using tf.io.serialize_tensor.

---------

Signed-off-by: EdwardCuiPeacock <Edward.Cui@nbcuni.com>