[ci] fix docbuild (#41197)
https://docs.scipy.org/doc/scipy/ is down, which cause docbuild to fail. Better to have a doc without reference to scipy than nothing.

Error: https://buildkite.com/ray-project/premerge/builds/11904#018bd5a7-0219-481c-be19-4472c5028173

Signed-off-by: can <can@anyscale.com>