[core][tune] fix RayTaskError (de)serialization logic (#54396)
Fixes a (de)serialization issue in `RayTaskError` that happens when the
original cause has its own `__reduce__` method defined.

```
TypeError: RayTaskError._make_normal_dual_exception_instance.<locals>.cls.__init__() takes 2 positional arguments but 3 were given
```


---------

Signed-off-by: Matthew Deng <matt@anyscale.com>