Fix '//:redis_client' build on RHEL 7.6 ppc64le
Default '-std=c++0x' flag for cpp compilation results in
errors in building msgpack which is a dependency for
redis_client. The error seen:
  external/msgpack/include/msgpack/v1/vrefbuffer.hpp:29:22:
     fatal error: Winsock2.h: No such file or directory
     #include <Winsock2.h>
This causes build failure for 'redis_client'.

Similar build issues were seen for '@plasma//:plasma_client'
with older commits of ray back in March 2020. Relevant PR:
https://github.com/ray-project/ray/pull/7828

Adding '-std=gnu++0x' to build flags fixes the build.