[Data] Fix failing `does_not_over_provision` release test  (#62320)
https://github.com/ray-project/ray/pull/61840 updated our benchmark
utility to track object store memory spilling. It's implementation calls
`ray.get_runtime_context()`, and that API implicitly starts a Ray
cluster.
 
Since the `does_not_over_provision` script explicitly calls
`ray.init()`, it started failing with this error:

```
results_working_dirs_does_not_over_provision_kmvkzybtvq__anyscale_pkg_bb2d7f959c995d17beba491351814253/autoscaling/does_not_over_provision.py", line 11, in main
--
ray.init()
File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 107, in wrapper
return func(*args, **kwargs)
File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/worker.py", line 1832, in init
raise RuntimeError(
RuntimeError: Maybe you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.
Subprocess return code: 1
```

To fix the failure, I've added a guard to check if Ray is initialized
before calling `ray.init()`. I've also changed the frequency to nightly
so that we capture failures in this test.

---------

Signed-off-by: Balaji Veeramani <bveeramani@berkeley.edu>