[core] avoid using podman pull to talk to docker api (#62142)
Fix CI test linux://python/ray/tests:test_runtime_env_container is
consistently_failing.

The docker engine was upgraded in the CI, and `podman pull
docker-daemon:{image}` had an error since then:
```
Error: initializing source docker-daemon:rayproject/ray:runtime_env_container: loading image from docker engine: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```

This PR fixes the issue by installing docker cli in the test image to
avoid using `podman pull docker-daemon:xxx` from the test container.


## Related issues
https://github.com/anyscale/ray/issues/1226
https://github.com/anyscale/ray/issues/1225
https://github.com/anyscale/ray/issues/1224
https://github.com/anyscale/ray/issues/1223
https://github.com/anyscale/ray/issues/1222
https://github.com/anyscale/ray/issues/1221
https://github.com/anyscale/ray/issues/1217
https://github.com/anyscale/ray/issues/1216
https://github.com/anyscale/ray/issues/1213
https://github.com/anyscale/ray/issues/1212
https://github.com/anyscale/ray/issues/1208
https://github.com/anyscale/ray/issues/1207
https://github.com/anyscale/ray/issues/1203
https://github.com/anyscale/ray/issues/1202
https://github.com/anyscale/ray/issues/1197
https://github.com/anyscale/ray/issues/1195
https://github.com/anyscale/ray/issues/1186
https://github.com/anyscale/ray/issues/1185
https://github.com/anyscale/ray/issues/1181
https://github.com/anyscale/ray/issues/1180
https://github.com/anyscale/ray/issues/1178

Signed-off-by: Rueian Huang <rueiancsie@gmail.com>