[Data] Fix streaming ingest benchmark (#40264)
The streaming_data_ingest_benchmark is failing with an error like this:

> TypeError: run_ingest_streaming() got an unexpected keyword argument 'fn_args'

This is because we pass in the positional arguments as a keyword argument, when we should just pass them in as normal positional arguments.

Signed-off-by: Balaji Veeramani <balaji@anyscale.com>