[Bug] Fix `object_store_memory` resolving as float when capped by shm (#63370)
## Description
When `object_store_memory` is not explicitly set,
`resolve_object_store_memory` can return a float on Linux because
`get_shared_memory_bytes() * 0.95` produces a float. This propagates
through to `ResourceIsolationConfig`, where int is expected.

Fix: wrap the shm calculation in int().

Add a test to catch the problem.
## Related issues
None.

## Additional information

The float value of `object_store_memory` causes cgroupv2 resource
isolation to fail, example error:
```
ERROR: illegal value '25827853721.6' specified for int64 flag 'system_reserved_memory_bytes'
```

Signed-off-by: madiyar-wayve <madiyar.aitzhanov@wayve.ai>
Co-authored-by: Kunchen (David) Dai <54918178+Kunchd@users.noreply.github.com>