[Nightly] fix microbenchmark scripts (#26947)
Signed-off-by: scv119 scv119@gmail.com

Why are these changes needed?
microbenchmarks failed complaining

   raise ValueError(f"Malformed address: {address}")
ValueError: Malformed address: 
this is due to 55a0f7b and fix it by set RAY_ADDRESS="local"