feat(build): add container-resource-utils
Feature required for building images locally and not running into OOMs. On my 14 core 24GB macbook, we spin up 14 jobs that result in OOM kills during cpp compilation+linking steps. This makes it take multiple attempts to build ray-core and ray-java locally.

For the above example of 14core 24GB, we cap to 7 jobs which is sustainable. Additionally, timing out a build from a freshly pruned state looks like this, so limiting jobs is not having a noticeable impact on wallclock. It's likely related to less resource contention, but I have not had time to dig into it further.

Longer term we will want to do a more Bazel-native way to tune builds. For now, we can defer to the heavy-hammer approach of capping jobs proportional to the amount of available memory.

For CI, this is a no-op, as the machines are expected to be beefy enough to not need these caps (as they are today).

export PYTHON_VERSION=3.13
export MANYLINUX_VERSION=260103.868e54c
export HOSTTYPE=aarch64
export ARCH_SUFFIX=-aarch64
export BUILDKITE_COMMIT=3cf4076a3e
export IS_LOCAL_BUILD=false

time wanda ci/docker/ray-core.wanda.yaml

failed at 5119.8 (05:22:24) [32mINFO: [0mElapsed time: 5089.441s, Critical Path: 1009.68s
ERROR: failed to build: failed to solve: ResourceExhausted: process "/bin/sh -c /dev/pipes/EOF" did not complete successfully: cannot allocate memory

export PYTHON_VERSION=3.13
export MANYLINUX_VERSION=260103.868e54c
export HOSTTYPE=aarch64
export ARCH_SUFFIX=-aarch64
export BUILDKITE_COMMIT=3cf4076a3e
export IS_LOCAL_BUILD=true

time wanda ci/docker/ray-core.wanda.yaml

12 2396.0 (16:10:16) [32mINFO:[0m Build completed successfully, 8104 total actions
12 DONE 2396.4s

Labels: draft
Topic: local-build-container-utils
Relative: wanda-specs
Signed-off-by: andrew <andrew@anyscale.com>