Try fixing the issue. (#29657)
Looks like we are using PyOpenSSL < 22.0 which can cause issues with the newer version of cryptography module that causes AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK' . Check boto/botocore#2744
urllib3/urllib3#2680
for more details.

The problem was that when we call install-dependencies, it downloads requirements.txt and then requirement_test.txt. When we download requirement_test.txt, we don't have -U flag, and then this means some of dependencies are not upgraded as stated inside requirement_test.txt. I tried adding -U flag to the PR

Signed-off-by: SangBin Cho <rkooo567@gmail.com>
Signed-off-by: Shomil Jain <shomil@anyscale.com>