[Job] [Python 3.11] fixes agent info container type (#36642)
Breaking change introduced in python 3.11 to the random package https://docs.python.org/3.11/library/random.html#random.sample

Sample throws a type error when passed a non-sequence object (in this case, a set).

This PR changes the set type to sorted, as per the error message:
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).

Fixes #36578

Signed-off-by: frazierprime <josh.frazier@sage.com>
Signed-off-by: e428265 <arvind.chandramouli@lmco.com>