[serve] Fix traceback string for RayTaskErrors when deploying serve app (#33120)
If a syntax error occurs when Serve tries to import a Serve application and deploy it, the error will not show up correctly on `serve status`. Specifically it just shows `ray.exceptions.RayTaskError(SyntaxError): <no detail available>`. This makes it hard for users to debug.

This is because for some reason `traceback.format_exc()` does not get the traceback string correctly for `RayTaskError`s; it seems to have it's own way of getting the traceback string [here](https://github.com/ray-project/ray/blob/a892241ca7574af47f278a667e6493a4b03686d7/python/ray/exceptions.py#L163). So we need to change `str(e)`.

Previously:
```
name: ''
app_status:
  status: DEPLOY_FAILED
  message: |
    Deployment failed:
    Traceback (most recent call last):
      File "/Users/cindyz/ray/python/ray/serve/_private/application_state.py", line 162, in update
        ray.get(finished[0])
      File "/Users/cindyz/ray/python/ray/_private/client_mode_hook.py", line 105, in wrapper
        return func(*args, **kwargs)
      File "/Users/cindyz/ray/python/ray/_private/worker.py", line 2384, in get
        raise value.as_instanceof_cause()
    ray.exceptions.RayTaskError(SyntaxError): <no detail available>
  deployment_timestamp: 1678228862.220114
deployment_statuses: []
```

With `str(e)`:
```
name: ''
app_status:
  status: DEPLOY_FAILED
  message: |-
    Deployment failed:
    ray::run_graph() (pid=81000, ip=10.104.98.7)
      File "/Users/cindyz/ray/python/ray/serve/controller.py", line 859, in run_graph
        graph = import_attr(import_path)
      File "/Users/cindyz/miniforge3/envs/ray/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 839, in exec_module
      File "<frozen importlib._bootstrap_external>", line 976, in get_code
      File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/Users/cindyz/Desktop/fail.py", line 4
        print("yo")
        ^
    SyntaxError: invalid syntax
  deployment_timestamp: 1678228961.0310981
deployment_statuses: []
```

Signed-off-by: Jack He <jackhe2345@gmail.com>