[Serve] Avoid killing replicas that are actively being deployed in `long_running_serve_failure` test (#31945)
The `long_running_serve_failure` release test is unstable and passes about 50% of the time. It seems to fail after a `.deploy()` call errors with the message:

```
Traceback (most recent call last):
  File "workloads/serve_failure.py", line 159, in <module>
    tester.run()
  File "workloads/serve_failure.py", line 130, in run
    action_chosen()
  File "workloads/serve_failure.py", line 107, in create_deployment
    handler.deploy()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/deployment.py", line 217, in deploy
    self._deploy(*init_args, _blocking=_blocking, **init_kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/deployment.py", line 244, in _deploy
    _blocking=_blocking,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/_private/client.py", line 37, in check
    return f(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/_private/client.py", line 238, in deploy
    self._wait_for_deployment_healthy(name)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/_private/client.py", line 174, in _wait_for_deployment_healthy
    f"Deployment {name} is UNHEALTHY: " f"{status.message}"
RuntimeError: Deployment InWRYtjoUK is UNHEALTHY: 
```

The deployment that's marked `UNHEALTHY` is always killed by the `RandomKiller` before this message appears. The issue is likely that:

1. The `RandomKiller` kills the deployment while it's still deploying
2. This causes the deployment to be [marked `UNHEALTHY`](https://github.com/ray-project/ray/blob/455100b54f0a82ce44dfa2257d40297c275424e0/python/ray/serve/_private/deployment_state.py#L1517-L1523)
3. This in turn causes [the `deploy()` call](https://github.com/ray-project/ray/blob/3735ba410ddfa63cc8516f69fa8b3997259a3f11/release/long_running_tests/workloads/serve_failure.py#L107) (and the test) [to raise an error and fail](https://github.com/ray-project/ray/blob/455100b54f0a82ce44dfa2257d40297c275424e0/python/ray/serve/_private/client.py#L172-L175).

This change guards against this by preventing the `RandomKiller` from kill the deployment while it's deploying.

Signed-off-by: Shomil Jain <shomil@anyscale.com>