[Doc] fix the tune's installation instruction in the getting started example (#30280)
Fix Ray tune's install instruction in the getting started example. https://docs.ray.io/en/latest/tune/getting-started.html
Currently, you will run into this error if you only install ray following the instruction.

ImportError: ray.tune in ray > 0.7.5 requires 'tabulate'. Please re-run 'pip install ray[tune]' or 'pip install ray[rllib]'.
I install ray tune and fixed it.

Signed-off-by: Huaiwei Sun <scottsun94@gmail.com>

Signed-off-by: Huaiwei Sun <scottsun94@gmail.com>
Signed-off-by: Shomil Jain <shomil@anyscale.com>