[core] Surface correct error message when `get_if_exists=True` (#58628)
## Description

```python
import ray
from ray.util.placement_group import placement_group
from ray.util.scheduling_strategies import PlacementGroupSchedulingStrategy

# Create a placement group.
pg = placement_group([{"CPU": 1}])
ray.get(pg.ready())

@ray.remote(num_cpus=1, num_gpus=8)
class Actor:
    def __init__(self):
        pass

actor = Actor.options(
    scheduling_strategy=PlacementGroupSchedulingStrategy(placement_group=pg),
    name="actor",
    get_if_exists=True,
).remote()
```

* Without this PR, you will get the following error message:
  ```
ValueError: Failed to look up actor with name 'actor'. This could
because 1. You are trying to look up a named actor you didn't create. 2.
The named actor died. 3. You did not use a namespace matching the
namespace of the actor.
  ```

* With this PR, you will get the actual root casue:
  ```
ValueError: Cannot schedule Actor with the placement group because the
resource request {'CPU': 1, 'GPU': 8} cannot fit into any bundles for
the placement group, [{'CPU': 1.0}].
  ```

## Related issues

## Additional information

---------

Signed-off-by: Kai-Hsun Chen <khchen@x.ai>
Signed-off-by: Edward Oakes <ed.nmi.oakes@gmail.com>
Co-authored-by: Edward Oakes <ed.nmi.oakes@gmail.com>
Signed-off-by: CesarRodrigu <128821412+CesarRodrigu@users.noreply.github.com>