[train] update `datasets` from `2.19.1` to `3.6.0` (#54338)
This fixes an issue in lower versions of `datasets` when trying to call
`load_datasets`.

### Changes
1. Bump `datasets` to `3.6.0`.
2. Bump other dependencies needed to make this work.
3. Recompile dependencies.
4. Update examples to use the new APIs.
5. Disable the huggingface test for `pyarrow v9` because the pinned
`datasets` version is explicitly incompatible.
6. Unpin dependencies introduced in the
https://github.com/ray-project/ray/pull/54425 stop-gap, and rely on the
global dependencies instead.

### Example

**Repro:**
```python
from datasets import load_dataset
load_dataset("tiny_shakespeare")
```

**Bad:**
```bash
(base) ray@ip-10-0-98-222:~/default$ pip install -q "datasets==3.0.1"
Successfully registered `datasets` package to be installed on all cluster nodes.
View and update dependencies here: https://console.anyscale-staging.com/cld_kvedZWag2qA8i5BjxUevf5i7/prj_92c7b71w55flm6gv6imv4m6vqg/workspaces/expwrk_hzadb7trab42qwqk8yumcx8tf2?workspace-tab=dependencies
(base) ray@ip-10-0-98-222:~/default$ python repro.py
Traceback (most recent call last):
  File "/home/ray/default/repro.py", line 2, in <module>
    load_dataset("tiny_shakespeare")
  File "/home/ray/anaconda3/lib/python3.9/site-packages/datasets/load.py", line 2074, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/datasets/load.py", line 1795, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/datasets/load.py", line 1671, in dataset_module_factory
    raise e1 from None
  File "/home/ray/anaconda3/lib/python3.9/site-packages/datasets/load.py", line 1617, in dataset_module_factory
    can_load_config_from_parquet_export = "DEFAULT_CONFIG_NAME" not in f.read()
  File "/home/ray/anaconda3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Good:**
```bash
(base) ray@ip-10-0-98-222:~/default$ pip install -q "datasets==3.0.2"
Successfully registered `datasets` package to be installed on all cluster nodes.
View and update dependencies here: https://console.anyscale-staging.com/cld_kvedZWag2qA8i5BjxUevf5i7/prj_92c7b71w55flm6gv6imv4m6vqg/workspaces/expwrk_hzadb7trab42qwqk8yumcx8tf2?workspace-tab=dependencies
(base) ray@ip-10-0-98-222:~/default$ python repro.py
The repository for tiny_shakespeare contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/tiny_shakespeare.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N]
```

---------

Signed-off-by: Matthew Deng <matt@anyscale.com>
Signed-off-by: jugalshah291 <shah.jugal291@gmail.com>