[CI] Fix deepspeed astral's cu128 index incompatible with Torch 2.9 (#65936)
## Description
https://github.com/ray-project/ray/pull/65899 added astral's cu128 index
for torch-scatter support, however, at the same time, started pulling in
a DeepSpeed wheel that was compiled with torch 2.11
This wheel is incompatible with our torch 2.9 install causing
```
RuntimeError: PyTorch version mismatch! DeepSpeed ops were compiled and installed with a different version than what is being used at runtime. Please re-install DeepSpeed or switch torch versions. Install torch version=2.11, Runtime torch version=2.9 
```

This PR fixes it through adding `--no-binary` to `uv` for `deepspeed` to
ensure that deepspeed is built locally using the current torch version.
In this future this could be removed.

Signed-off-by: Mark Towers <mark@anyscale.com>
Co-authored-by: Mark Towers <mark@anyscale.com>