[ray.llm.batch][Bugfix] ValueError: 'data_column' cannot be used as in fn_constructor_kwargs (#50926)
## Why are these changes needed?

Hitting this bug when applying a processor to more than one datasets:

```
ValueError: 'data_column' cannot be used as in fn_constructor_kwargs.
```

The root cause is we should not update `self.fn_constructor_kwargs` in
`get_dataset_map_batches_kwargs`.

cc @SumanthRH 

## Related issue number

N/A

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git
commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for
https://docs.ray.io/en/master/.
- [x] I've added any new APIs to the API Reference. For example, if I
added a
method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a
few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

Signed-off-by: Cody Yu <hao.yu.cody@gmail.com>