[Data] Retry access denied error when opening file (#42806)
User found AWS S3 would throw error like below when opening file. This is also due to try to open too many files at same time. So add the error message here to allow auto retry.

```
OSError: When reading information for key ... in bucket ...: AWS Error ACCESS_DENIED during HeadObject operation: No response body.
```

Signed-off-by: Cheng Su <scnju13@gmail.com>