[Autoscaler] Bump ebs volume size in default configs (#32708)
Why are these changes needed?
The defaul volume size was too small and caused an error; this PR bumps it to 140gb as specified in the error message:
ray.autoscaler.node_launch_exception.NodeLaunchException: Node Launch Exception (InvalidBlockDeviceMapping): Volume of size 100GB is smaller than snapshot 'snap-04db122cb9d19ae16', expect size >= 140GB
We currently don't have tests to catch these regressions, but we plan to add them.

Related issue number
Closes #32707

---------

Signed-off-by: Archit Kulkarni <architkulkarni@users.noreply.github.com>