PR 31978 replaced result_output_json and metrics_output_json with fixed values, but did not update client_runner. GCE tests using client_runner is failing with the following error because of that. Simple fix by reusing the fixed global values.
> [Errno 2] No such file or directory: '/tmp/tmpr33nmui3'
> Traceback (most recent call last):
>  File "/tmp/release-HS2M44AnMX/release/ray_release/command_runner/client_runner.py", line 122, in _fetch_json
>    with open(path, "rt") as fp:
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpr33nmui3'

Signed-off-by: Cuong Nguyen <can@anyscale.com>