[llm][deps] Upgrade vLLM to 0.20.0 (#62970)
## Description
### CI/REEf-related
- Switch LLM CI and release tests to run on python 3.12 + cuda 13
images.
- Remove `LD_LIBRARY_PATH` hacks in `ci/docker/llm.build.Dockerfile` and
`docker/ray-llm/Dockerfile`.
- `anyscale` is pinned to `0.26.97` on the `llm-cu130` image. In this
version, `anyscale.job.status()` fetches job runs through a new internal
endpoint (`POST /api/v2/decorated_ha_jobs/job_runs/search`) which
requires an API key, but the release test is running inside an Anyscale
job with only the cluster CLI token. This results in the following error
([sample
log](https://console.anyscale-staging.com/cld_wy5a6nhazplvu32526ams61d98/prj_lhlrf1u5yv8qz9qg3xzw8fkiiq/jobs/prodjob_rcgpimwr11kgmr6t3w3cr6rpdn?job-logs-section-tabs=application_logs&job-tab=overview)).
Fixed via
https://github.com/ray-project/ray/pull/62970/commits/6884f778ce2a5cf6593338928d2655f7318ad6f4.
```
ValueError: The endpoint POST /api/v2/decorated_ha_jobs/job_runs/search requires a different type of authentication, please use your API key instead of the cluster CLI token.
```

### LLM-related
- Ray worker class is renamed to `RayWorkerProc` in vLLM, resulting in
changes in `release/llm_tests/serve/test_llm_serve_dp_engine_fault.py`.
- vLLM breaking APIs. Please refer to code diffs for more details.
- vLLM 0.20 requires `NIXL >=0.7.1, <=0.10.1`
([reference](https://github.com/vllm-project/vllm/blob/v0.20.0/requirements/kv_connectors.txt#L2)).
Therefore we apply the same constraints in
`python/requirements/llm/llm-requirements.txt`.
- Batch benchmark import failure: `huggingface-hub==1.5.0` conflicted
with the installed transformers, which requires <1.0. Added
huggingface-hub<1.0 for py3.12 batch requirements
([code](release/llm_tests/batch/requirements.in)). See
[thread](https://github.com/ray-project/ray/pull/62970#discussion_r3185122346).
- **Why we need all `nixl[cu13]`, `nixl-cu12`, and `nixl-cu13` as
dependencies?**
- We need `nixl[cu13]` because vLLM imports `nixl`. The plain
`nixl-cu13` package only provides the CUDA 13 backend module, not the
top-level import `nixl` shim.
- We need `nixl-cu12` because `nixl==0.10.1` has a default dependency on
`nixl-cu12>=0.10.1,` even when installing `nixl[cu13]`. Pinning/capping
it keeps the resolver from selecting a newer incompatible `nixl-cu12`
like 1.x.
- `nixl-cu13` is the CUDA 13 backend we actually want on the CU13
release image.



## Related issues
> Link related issues: "Fixes #1234", "Closes #1234", or "Related to
#1234".

## Additional information
> Optional: Add implementation details, API changes, usage examples,
screenshots, etc.

---------

Signed-off-by: Jeffrey Wang <jeffreywang@anyscale.com>
Signed-off-by: jeffreywang-anyscale <jeffreywang@anyscale.com>