Add descriptive error message when deployment name not found (#45181)
## Why are these changes needed?

If the named deployment isn't found in a Ray serve instance, it's
difficult to troubleshoot the names of deployments that are available.
This error lists the known ones out in the error message instead.

For example, we now can see:

```
ray.serve.exceptions.RayServeException: Deployment 'capitalizer' for application 'capitalizer' 
does not exist. Available: ['Capitalizer', 'Uncapitalizer', 'CapitalizerEndpoint']
```

vs. previously:

```
(ServeController pid=99265)   File ... error in override_deployment_info
(ServeController pid=99265)     info = deployment_infos[deployment_name]
(ServeController pid=99265)            ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
(ServeController pid=99265) KeyError: 'capitalizer'
```


## Related issue number

<!-- For example: "Closes #1234" -->

(N/A)

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git
commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] ~~I've included any doc changes needed for
https://docs.ray.io/en/master/.~~
- [ ] ~~I've added any new APIs to the API Reference. For example, if I
added a
method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.~~
- [X] I've made sure the tests are passing. Note that there might be a
few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

---------

Signed-off-by: Brandon Shelley <brandon@pacificaviator.co>
Signed-off-by: Seiji Eicher <seiji@anyscale.com>
Co-authored-by: Seiji Eicher <seiji@anyscale.com>