[core] Don't try to monitor zipped files (#53151)
## Why are these changes needed?
Some users may implement their own log rotation on autoscaler event
files. If zipping the files during rotation, the event agent will still
try to read zipped files and raise an exception causing that file
monitor to fail. We try to open the files every 0.1 seconds. We only
need to look for new events in .log files that are actively being
written to.

This pr prevents opening and looking for changes in zipped files. There
will be no further changes in these files, so we don't need to monitor
them. This can lead to exceptions like
```
Exception: Read event file failed: /tmp/ray/session_2025-04-30_09-40-39_975641_2270/logs/events/event_AUTOSCALER.log.2.gz
    raise Exception(f"Read event file failed: {file}") from e
File "/home/ray/anaconda3/lib/python3.12/site-packages/ray/dashboard/modules/event/event_utils.py", line 176, in
_read_monitor_file
```

### Future state
Long term we'll kill this event agent / head entirely with the new
observability stack, and Ray will stop writing events to files. Any
events should follow a similar path to the new task events. An rpc with
events should be sent to the gcs from the component emitting the events
and the events will eventually get persisted in some storage, users can
plug-in their own storage to persist.

---------

Signed-off-by: dayshah <dhyey2019@gmail.com>
Signed-off-by: Douglas Strodtman <douglas@anyscale.com>